### ISSUE TITLE
wavplayer hangs on RPI Pico

### ISSUE THREAD

**Issue by roddersuk** [miketeachman/micropython-esp32-i2s-examples#30]
Tried running wavplayer on my Pico and it starts playing fine but after a few seconds it crashes the Pico with this traceback:
```
Traceback (most recent call last):
  File "wavplayer.py", line 61, in i2s_callback
  File "sdcard.py", line 273, in readblocks
OSError: [Errno 5] `EIO
`````
The ``only variation from your setup is that I use gpio 10,11,12 for the SD card instead of 14,15,12
I have to reboot the Pico to recover
Any ideas?

**Comment by roddersuk** [comment]
I think this was dodgy wiring on my breadboard causing the SD card reader to fail.
